#ifndef CMD_TYPES_H
#define CMD_TYPES_H

enum CommandTypes {
    SET_POS_GAINS,
    SET_POS_SETPOINT,
    START_POS_PID,
    STOP_POS_PID,
    SEND_TOF_DATA,
    SEND_POS_PID_CONTROL_DATA,
    PID_SPEED_TEST,
    PING_SPEED_TEST,
    SET_ANGLE_GAINS,
    SET_ANGLE_SETPOINT,
    START_ANGLE_PID,
    STOP_ANGLE_PID,
    SEND_IMU_DATA,
    SEND_ANGLE_PID_CONTROL_DATA,
    START_OPEN_LOOP,
    FETCH_D1,
};

#endif // CMD_TYPES_H